# Generated by Django 3.1.4 on 2022-08-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('core_values', models.CharField(blank=True, default='Core Values', max_length=250, null=True)),
                ('bio', models.CharField(blank=True, default='Bio', max_length=250, null=True)),
                ('mission', models.CharField(blank=True, default='mission', max_length=250, null=True)),
                ('vision', models.CharField(blank=True, default='vision', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='horlamy007@gmail.com', max_length=254)),
                ('location', models.CharField(blank=True, default='Nigeria', max_length=250, null=True)),
                ('phone', models.CharField(blank=True, default='09029320231', max_length=250, null=True)),
            ],
        ),
    ]
