# Generated by Django 3.1.4 on 2022-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_admin', '0002_auto_20220909_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('category', models.CharField(choices=[('Fixed', 'Fixed'), ('Negotiable', 'Negotiable')], default='Fixed', max_length=20)),
            ],
        ),
    ]
